/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    //Build tests for transformations

    String filePath = "assets/mario.bmp";

    @Test
    public void testRandomize() {
        File file = new File(pathToFile);
        Bitmap bitmap = new Bitmap(file);
}
