/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    //Write code to read in a bitmap file (hardcoded String)

    //Write out that unchanged bitmap into a file with a different name (hardcoded String)

    //Run the application to make sure read and write of bitmap file is possible

    //Create Bitmap class with constructor and instance method to write out image data

    //Move code from main method into Bitmap class, create Bitmap object in main method, write it out to a different file name (hardcoded String)

    //Run the application to make sure that it can still be read and then write file that code abstracts

    //Write a transform method (set every red pixel to green)

    //Call the transform method in main method and ensure that bitmap can be read and be written out as a bitmap file that is the same size but with red replaced with green

    //Start working with command line arguments. Start by making the output file path a command line argument and ensure it works.

    //Add a second transform to try a second transformation

    //Build tests for transformations

    //Continue creating transform methods and tests to match
    
}
public static getFile(){

        }
